// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ad_sets.sql

package db

import (
	"context"
	"database/sql"
)

const createAdSet = `-- name: CreateAdSet :one
INSERT INTO ad_sets (
    campaign_id,
    name,
    bid_amount_cents,
    daily_budget_cents,
    pricing_model
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, campaign_id, name, bid_amount_cents, daily_budget_cents, pricing_model, created_at, updated_at
`

type CreateAdSetParams struct {
	CampaignID       sql.NullInt32  `json:"campaign_id"`
	Name             sql.NullString `json:"name"`
	BidAmountCents   sql.NullInt64  `json:"bid_amount_cents"`
	DailyBudgetCents sql.NullInt64  `json:"daily_budget_cents"`
	PricingModel     sql.NullString `json:"pricing_model"`
}

func (q *Queries) CreateAdSet(ctx context.Context, arg CreateAdSetParams) (AdSet, error) {
	row := q.db.QueryRowContext(ctx, createAdSet,
		arg.CampaignID,
		arg.Name,
		arg.BidAmountCents,
		arg.DailyBudgetCents,
		arg.PricingModel,
	)
	var i AdSet
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.BidAmountCents,
		&i.DailyBudgetCents,
		&i.PricingModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdSet = `-- name: GetAdSet :one
SELECT id, campaign_id, name, bid_amount_cents, daily_budget_cents, pricing_model, created_at, updated_at FROM ad_sets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAdSet(ctx context.Context, id int32) (AdSet, error) {
	row := q.db.QueryRowContext(ctx, getAdSet, id)
	var i AdSet
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.BidAmountCents,
		&i.DailyBudgetCents,
		&i.PricingModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdSetsByCampaign = `-- name: ListAdSetsByCampaign :many
SELECT id, campaign_id, name, bid_amount_cents, daily_budget_cents, pricing_model, created_at, updated_at FROM ad_sets
WHERE campaign_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAdSetsByCampaign(ctx context.Context, campaignID sql.NullInt32) ([]AdSet, error) {
	rows, err := q.db.QueryContext(ctx, listAdSetsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdSet
	for rows.Next() {
		var i AdSet
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.BidAmountCents,
			&i.DailyBudgetCents,
			&i.PricingModel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
