// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ads.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createAd = `-- name: CreateAd :one
INSERT INTO ads (ad_set_id,
                 headline,
                 description,
                 creative_type,
                 media_url,
                 destination_url,
                 status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, ad_set_id, headline, description, creative_type, media_url, destination_url, status, created_at, updated_at
`

type CreateAdParams struct {
	AdSetID        sql.NullInt32  `json:"ad_set_id"`
	Headline       sql.NullString `json:"headline"`
	Description    sql.NullString `json:"description"`
	CreativeType   sql.NullString `json:"creative_type"`
	MediaUrl       sql.NullString `json:"media_url"`
	DestinationUrl sql.NullString `json:"destination_url"`
	Status         string         `json:"status"`
}

func (q *Queries) CreateAd(ctx context.Context, arg CreateAdParams) (Ad, error) {
	row := q.db.QueryRowContext(ctx, createAd,
		arg.AdSetID,
		arg.Headline,
		arg.Description,
		arg.CreativeType,
		arg.MediaUrl,
		arg.DestinationUrl,
		arg.Status,
	)
	var i Ad
	err := row.Scan(
		&i.ID,
		&i.AdSetID,
		&i.Headline,
		&i.Description,
		&i.CreativeType,
		&i.MediaUrl,
		&i.DestinationUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAd = `-- name: GetAd :one
SELECT id, ad_set_id, headline, description, creative_type, media_url, destination_url, status, created_at, updated_at
FROM ads
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAd(ctx context.Context, id int32) (Ad, error) {
	row := q.db.QueryRowContext(ctx, getAd, id)
	var i Ad
	err := row.Scan(
		&i.ID,
		&i.AdSetID,
		&i.Headline,
		&i.Description,
		&i.CreativeType,
		&i.MediaUrl,
		&i.DestinationUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdWithTargeting = `-- name: GetAdWithTargeting :one
SELECT a.id,
       a.ad_set_id,
       a.headline,
       a.description,
       a.creative_type,
       a.media_url,
       a.destination_url,
       a.status,
       a.created_at,
       a.updated_at
FROM ads a
WHERE a.id = $1
  AND a.status = 'ACTIVE'
LIMIT 1
`

func (q *Queries) GetAdWithTargeting(ctx context.Context, id int32) (Ad, error) {
	row := q.db.QueryRowContext(ctx, getAdWithTargeting, id)
	var i Ad
	err := row.Scan(
		&i.ID,
		&i.AdSetID,
		&i.Headline,
		&i.Description,
		&i.CreativeType,
		&i.MediaUrl,
		&i.DestinationUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAds = `-- name: ListActiveAds :many
SELECT id, ad_set_id, headline, description, creative_type, media_url, destination_url, status, created_at, updated_at
FROM ads
WHERE status = 'ACTIVE'
ORDER BY updated_at DESC
`

func (q *Queries) ListActiveAds(ctx context.Context) ([]Ad, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ad
	for rows.Next() {
		var i Ad
		if err := rows.Scan(
			&i.ID,
			&i.AdSetID,
			&i.Headline,
			&i.Description,
			&i.CreativeType,
			&i.MediaUrl,
			&i.DestinationUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdsByAdSet = `-- name: ListAdsByAdSet :many
SELECT id, ad_set_id, headline, description, creative_type, media_url, destination_url, status, created_at, updated_at
FROM ads
WHERE ad_set_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAdsByAdSet(ctx context.Context, adSetID sql.NullInt32) ([]Ad, error) {
	rows, err := q.db.QueryContext(ctx, listAdsByAdSet, adSetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ad
	for rows.Next() {
		var i Ad
		if err := rows.Scan(
			&i.ID,
			&i.AdSetID,
			&i.Headline,
			&i.Description,
			&i.CreativeType,
			&i.MediaUrl,
			&i.DestinationUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActiveAdsForIndex = `-- name: ListAllActiveAdsForIndex :many
SELECT a.id,
       a.ad_set_id,
       a.headline,
       a.description,
       a.creative_type,
       a.media_url,
       a.destination_url,
       a.status,
       ads.bid_amount_cents,
       ads.daily_budget_cents,
       ads.pricing_model,
       c.id     as campaign_id,
       c.advertiser_id,
       c.status as campaign_status,
       c.start_date,
       c.end_date,
       a.created_at,
       a.updated_at
FROM ads a
         JOIN ad_sets ads ON a.ad_set_id = ads.id
         JOIN campaigns c ON ads.campaign_id = c.id
WHERE a.status = 'ACTIVE'
  AND c.status = 'ACTIVE'
  AND c.start_date <= NOW()
  AND (c.end_date IS NULL OR c.end_date > NOW())
`

type ListAllActiveAdsForIndexRow struct {
	ID               int32          `json:"id"`
	AdSetID          sql.NullInt32  `json:"ad_set_id"`
	Headline         sql.NullString `json:"headline"`
	Description      sql.NullString `json:"description"`
	CreativeType     sql.NullString `json:"creative_type"`
	MediaUrl         sql.NullString `json:"media_url"`
	DestinationUrl   sql.NullString `json:"destination_url"`
	Status           string         `json:"status"`
	BidAmountCents   sql.NullInt64  `json:"bid_amount_cents"`
	DailyBudgetCents sql.NullInt64  `json:"daily_budget_cents"`
	PricingModel     sql.NullString `json:"pricing_model"`
	CampaignID       int32          `json:"campaign_id"`
	AdvertiserID     sql.NullInt32  `json:"advertiser_id"`
	CampaignStatus   string         `json:"campaign_status"`
	StartDate        time.Time      `json:"start_date"`
	EndDate          sql.NullTime   `json:"end_date"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}

func (q *Queries) ListAllActiveAdsForIndex(ctx context.Context) ([]ListAllActiveAdsForIndexRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllActiveAdsForIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllActiveAdsForIndexRow
	for rows.Next() {
		var i ListAllActiveAdsForIndexRow
		if err := rows.Scan(
			&i.ID,
			&i.AdSetID,
			&i.Headline,
			&i.Description,
			&i.CreativeType,
			&i.MediaUrl,
			&i.DestinationUrl,
			&i.Status,
			&i.BidAmountCents,
			&i.DailyBudgetCents,
			&i.PricingModel,
			&i.CampaignID,
			&i.AdvertiserID,
			&i.CampaignStatus,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangedAdsForIndex = `-- name: ListChangedAdsForIndex :many
SELECT a.id,
       a.ad_set_id,
       a.headline,
       a.description,
       a.creative_type,
       a.media_url,
       a.destination_url,
       a.status,
       ads.bid_amount_cents,
       ads.daily_budget_cents,
       ads.pricing_model,
       c.id     as campaign_id,
       c.advertiser_id,
       c.status as campaign_status,
       c.start_date,
       c.end_date,
       a.created_at,
       a.updated_at
FROM ads a
         JOIN ad_sets ads ON a.ad_set_id = ads.id
         JOIN campaigns c ON ads.campaign_id = c.id
WHERE a.id IN (SELECT DISTINCT a.id
               FROM ads a
                        JOIN ad_sets ads ON a.ad_set_id = ads.id
                        JOIN campaigns c ON ads.campaign_id = c.id
               WHERE a.updated_at > $1
                  OR ads.updated_at > $1
                  OR c.updated_at > $1)
`

type ListChangedAdsForIndexRow struct {
	ID               int32          `json:"id"`
	AdSetID          sql.NullInt32  `json:"ad_set_id"`
	Headline         sql.NullString `json:"headline"`
	Description      sql.NullString `json:"description"`
	CreativeType     sql.NullString `json:"creative_type"`
	MediaUrl         sql.NullString `json:"media_url"`
	DestinationUrl   sql.NullString `json:"destination_url"`
	Status           string         `json:"status"`
	BidAmountCents   sql.NullInt64  `json:"bid_amount_cents"`
	DailyBudgetCents sql.NullInt64  `json:"daily_budget_cents"`
	PricingModel     sql.NullString `json:"pricing_model"`
	CampaignID       int32          `json:"campaign_id"`
	AdvertiserID     sql.NullInt32  `json:"advertiser_id"`
	CampaignStatus   string         `json:"campaign_status"`
	StartDate        time.Time      `json:"start_date"`
	EndDate          sql.NullTime   `json:"end_date"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}

func (q *Queries) ListChangedAdsForIndex(ctx context.Context, updatedAt sql.NullTime) ([]ListChangedAdsForIndexRow, error) {
	rows, err := q.db.QueryContext(ctx, listChangedAdsForIndex, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChangedAdsForIndexRow
	for rows.Next() {
		var i ListChangedAdsForIndexRow
		if err := rows.Scan(
			&i.ID,
			&i.AdSetID,
			&i.Headline,
			&i.Description,
			&i.CreativeType,
			&i.MediaUrl,
			&i.DestinationUrl,
			&i.Status,
			&i.BidAmountCents,
			&i.DailyBudgetCents,
			&i.PricingModel,
			&i.CampaignID,
			&i.AdvertiserID,
			&i.CampaignStatus,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdStatus = `-- name: UpdateAdStatus :one
UPDATE ads
SET status = $2
WHERE id = $1
RETURNING id, ad_set_id, headline, description, creative_type, media_url, destination_url, status, created_at, updated_at
`

type UpdateAdStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateAdStatus(ctx context.Context, arg UpdateAdStatusParams) (Ad, error) {
	row := q.db.QueryRowContext(ctx, updateAdStatus, arg.ID, arg.Status)
	var i Ad
	err := row.Scan(
		&i.ID,
		&i.AdSetID,
		&i.Headline,
		&i.Description,
		&i.CreativeType,
		&i.MediaUrl,
		&i.DestinationUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
