// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: advertisers.sql

package db

import (
	"context"
	"database/sql"
)

const createAdvertiser = `-- name: CreateAdvertiser :one
INSERT INTO advertisers (name, website)
VALUES ($1, $2)
RETURNING id, name, website, created_at, updated_at
`

type CreateAdvertiserParams struct {
	Name    string         `json:"name"`
	Website sql.NullString `json:"website"`
}

func (q *Queries) CreateAdvertiser(ctx context.Context, arg CreateAdvertiserParams) (Advertiser, error) {
	row := q.db.QueryRowContext(ctx, createAdvertiser, arg.Name, arg.Website)
	var i Advertiser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAdvertiser = `-- name: DeleteAdvertiser :exec
DELETE FROM advertisers
WHERE id = $1
`

func (q *Queries) DeleteAdvertiser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteAdvertiser, id)
	return err
}

const getAdvertiser = `-- name: GetAdvertiser :one
SELECT id, name, website, created_at, updated_at FROM advertisers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAdvertiser(ctx context.Context, id int32) (Advertiser, error) {
	row := q.db.QueryRowContext(ctx, getAdvertiser, id)
	var i Advertiser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdvertisers = `-- name: ListAdvertisers :many
SELECT id, name, website, created_at, updated_at FROM advertisers
ORDER BY created_at DESC
`

func (q *Queries) ListAdvertisers(ctx context.Context) ([]Advertiser, error) {
	rows, err := q.db.QueryContext(ctx, listAdvertisers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Advertiser
	for rows.Next() {
		var i Advertiser
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Website,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdvertiser = `-- name: UpdateAdvertiser :one
UPDATE advertisers
SET name = $2, website = $3
WHERE id = $1
RETURNING id, name, website, created_at, updated_at
`

type UpdateAdvertiserParams struct {
	ID      int32          `json:"id"`
	Name    string         `json:"name"`
	Website sql.NullString `json:"website"`
}

func (q *Queries) UpdateAdvertiser(ctx context.Context, arg UpdateAdvertiserParams) (Advertiser, error) {
	row := q.db.QueryRowContext(ctx, updateAdvertiser, arg.ID, arg.Name, arg.Website)
	var i Advertiser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
