// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaigns.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (
    advertiser_id,
    name,
    status,
    total_budget,
    start_date,
    end_date
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, advertiser_id, name, status, total_budget, start_date, end_date, created_at, updated_at
`

type CreateCampaignParams struct {
	AdvertiserID sql.NullInt32 `json:"advertiser_id"`
	Name         string        `json:"name"`
	Status       string        `json:"status"`
	TotalBudget  sql.NullInt64 `json:"total_budget"`
	StartDate    time.Time     `json:"start_date"`
	EndDate      sql.NullTime  `json:"end_date"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, createCampaign,
		arg.AdvertiserID,
		arg.Name,
		arg.Status,
		arg.TotalBudget,
		arg.StartDate,
		arg.EndDate,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.AdvertiserID,
		&i.Name,
		&i.Status,
		&i.TotalBudget,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :exec
DELETE FROM campaigns
WHERE id = $1
`

func (q *Queries) DeleteCampaign(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCampaign, id)
	return err
}

const getActiveCampaigns = `-- name: GetActiveCampaigns :many
SELECT id, advertiser_id, name, status, total_budget, start_date, end_date, created_at, updated_at FROM campaigns
WHERE status = 'ACTIVE'
AND start_date <= NOW()
AND (end_date IS NULL OR end_date >= NOW())
ORDER BY created_at DESC
`

func (q *Queries) GetActiveCampaigns(ctx context.Context) ([]Campaign, error) {
	rows, err := q.db.QueryContext(ctx, getActiveCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.AdvertiserID,
			&i.Name,
			&i.Status,
			&i.TotalBudget,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, advertiser_id, name, status, total_budget, start_date, end_date, created_at, updated_at FROM campaigns
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCampaign(ctx context.Context, id int32) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, getCampaign, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.AdvertiserID,
		&i.Name,
		&i.Status,
		&i.TotalBudget,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, advertiser_id, name, status, total_budget, start_date, end_date, created_at, updated_at FROM campaigns
ORDER BY created_at DESC
`

func (q *Queries) ListCampaigns(ctx context.Context) ([]Campaign, error) {
	rows, err := q.db.QueryContext(ctx, listCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.AdvertiserID,
			&i.Name,
			&i.Status,
			&i.TotalBudget,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignsByAdvertiser = `-- name: ListCampaignsByAdvertiser :many
SELECT id, advertiser_id, name, status, total_budget, start_date, end_date, created_at, updated_at FROM campaigns
WHERE advertiser_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCampaignsByAdvertiser(ctx context.Context, advertiserID sql.NullInt32) ([]Campaign, error) {
	rows, err := q.db.QueryContext(ctx, listCampaignsByAdvertiser, advertiserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.AdvertiserID,
			&i.Name,
			&i.Status,
			&i.TotalBudget,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns
SET
    name = $2,
    status = $3,
    total_budget = $4,
    start_date = $5,
    end_date = $6
WHERE id = $1
RETURNING id, advertiser_id, name, status, total_budget, start_date, end_date, created_at, updated_at
`

type UpdateCampaignParams struct {
	ID          int32         `json:"id"`
	Name        string        `json:"name"`
	Status      string        `json:"status"`
	TotalBudget sql.NullInt64 `json:"total_budget"`
	StartDate   time.Time     `json:"start_date"`
	EndDate     sql.NullTime  `json:"end_date"`
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, updateCampaign,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.TotalBudget,
		arg.StartDate,
		arg.EndDate,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.AdvertiserID,
		&i.Name,
		&i.Status,
		&i.TotalBudget,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :one
UPDATE campaigns
SET status = $2
WHERE id = $1
RETURNING id, advertiser_id, name, status, total_budget, start_date, end_date, created_at, updated_at
`

type UpdateCampaignStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, updateCampaignStatus, arg.ID, arg.Status)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.AdvertiserID,
		&i.Name,
		&i.Status,
		&i.TotalBudget,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
