// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Ad struct {
	ID             int32          `json:"id"`
	AdSetID        sql.NullInt32  `json:"ad_set_id"`
	Headline       sql.NullString `json:"headline"`
	Description    sql.NullString `json:"description"`
	CreativeType   sql.NullString `json:"creative_type"`
	MediaUrl       sql.NullString `json:"media_url"`
	DestinationUrl sql.NullString `json:"destination_url"`
	Status         string         `json:"status"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type AdEmbedding struct {
	ID        int64        `json:"id"`
	AdID      int32        `json:"ad_id"`
	Embedding interface{}  `json:"embedding"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type AdSet struct {
	ID               int32          `json:"id"`
	CampaignID       sql.NullInt32  `json:"campaign_id"`
	Name             sql.NullString `json:"name"`
	BidAmountCents   sql.NullInt64  `json:"bid_amount_cents"`
	DailyBudgetCents sql.NullInt64  `json:"daily_budget_cents"`
	PricingModel     sql.NullString `json:"pricing_model"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}

type AdTargetingCountry struct {
	ID             int64         `json:"id"`
	AdID           sql.NullInt32 `json:"ad_id"`
	CountryIsoCode string        `json:"country_iso_code"`
	UpdatedAt      sql.NullTime  `json:"updated_at"`
}

type AdTargetingDevice struct {
	ID         int64         `json:"id"`
	AdID       sql.NullInt32 `json:"ad_id"`
	DeviceType string        `json:"device_type"`
	UpdatedAt  sql.NullTime  `json:"updated_at"`
}

type AdTargetingEntity struct {
	ID         int64         `json:"id"`
	AdID       sql.NullInt32 `json:"ad_id"`
	EntityID   string        `json:"entity_id"`
	EntityType string        `json:"entity_type"`
	UpdatedAt  sql.NullTime  `json:"updated_at"`
}

type AdTargetingKeyword struct {
	ID             int64          `json:"id"`
	AdID           sql.NullInt32  `json:"ad_id"`
	Keyword        string         `json:"keyword"`
	RelevanceScore sql.NullString `json:"relevance_score"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type AdTargetingTopic struct {
	ID             int64          `json:"id"`
	AdID           sql.NullInt32  `json:"ad_id"`
	TopicID        int32          `json:"topic_id"`
	RelevanceScore sql.NullString `json:"relevance_score"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type AdsAnalyticsAdClickEvent struct {
	ID          int64          `json:"id"`
	EventTime   time.Time      `json:"event_time"`
	AdID        int32          `json:"ad_id"`
	CampaignID  int32          `json:"campaign_id"`
	AuctionID   sql.NullString `json:"auction_id"`
	PublisherID sql.NullString `json:"publisher_id"`
	PageUrl     sql.NullString `json:"page_url"`
	ClickUrl    sql.NullString `json:"click_url"`
	PriceCents  sql.NullInt64  `json:"price_cents"`
	DeviceType  sql.NullString `json:"device_type"`
	UserAgent   sql.NullString `json:"user_agent"`
	IpAddress   pqtype.Inet    `json:"ip_address"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type AdsAnalyticsAdImpressionEvent struct {
	ID          int64          `json:"id"`
	EventTime   time.Time      `json:"event_time"`
	AdID        int32          `json:"ad_id"`
	CampaignID  int32          `json:"campaign_id"`
	AuctionID   sql.NullString `json:"auction_id"`
	PublisherID sql.NullString `json:"publisher_id"`
	PageUrl     sql.NullString `json:"page_url"`
	PriceCents  sql.NullInt64  `json:"price_cents"`
	DeviceType  sql.NullString `json:"device_type"`
	UserAgent   sql.NullString `json:"user_agent"`
	IpAddress   pqtype.Inet    `json:"ip_address"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type AdsAnalyticsAdMetricsHourly struct {
	Hour        int64 `json:"hour"`
	AdID        int32 `json:"ad_id"`
	CampaignID  int32 `json:"campaign_id"`
	Impressions int64 `json:"impressions"`
	Clicks      int64 `json:"clicks"`
	SpendCents  int64 `json:"spend_cents"`
	AvgEcpm     int32 `json:"avg_ecpm"`
	AvgCtr      int32 `json:"avg_ctr"`
}

type AdsAnalyticsAuctionEvent struct {
	ID                   int64          `json:"id"`
	EventTime            time.Time      `json:"event_time"`
	AuctionID            string         `json:"auction_id"`
	PublisherID          sql.NullString `json:"publisher_id"`
	PageUrl              sql.NullString `json:"page_url"`
	NumCandidates        sql.NullInt32  `json:"num_candidates"`
	NumFilteredBudget    sql.NullInt32  `json:"num_filtered_budget"`
	NumFilteredTargeting sql.NullInt32  `json:"num_filtered_targeting"`
	NumEligible          sql.NullInt32  `json:"num_eligible"`
	WinnerAdID           sql.NullInt32  `json:"winner_ad_id"`
	WinnerCampaignID     sql.NullInt32  `json:"winner_campaign_id"`
	WinningBidCents      sql.NullInt64  `json:"winning_bid_cents"`
	WinningEffectiveBid  sql.NullString `json:"winning_effective_bid"`
	WinningFinalScore    sql.NullString `json:"winning_final_score"`
	DeviceType           sql.NullString `json:"device_type"`
	UserAgent            sql.NullString `json:"user_agent"`
	IpAddress            pqtype.Inet    `json:"ip_address"`
	CreatedAt            sql.NullTime   `json:"created_at"`
}

type AdsAnalyticsAuctionMetricsHourly struct {
	Hour                  int64   `json:"hour"`
	TotalAuctions         int64   `json:"total_auctions"`
	AuctionsWithWinner    int64   `json:"auctions_with_winner"`
	AvgCandidates         float64 `json:"avg_candidates"`
	AvgFilteredBudget     float64 `json:"avg_filtered_budget"`
	AvgFilteredTargeting  float64 `json:"avg_filtered_targeting"`
	AvgEligible           float64 `json:"avg_eligible"`
	AvgWinningBidCents    float64 `json:"avg_winning_bid_cents"`
	MedianWinningBidCents float64 `json:"median_winning_bid_cents"`
	FillRatePct           int32   `json:"fill_rate_pct"`
}

type AdsAnalyticsCampaignMetricsHourly struct {
	Hour        int64 `json:"hour"`
	CampaignID  int32 `json:"campaign_id"`
	Impressions int64 `json:"impressions"`
	Clicks      int64 `json:"clicks"`
	SpendCents  int64 `json:"spend_cents"`
	AvgEcpm     int32 `json:"avg_ecpm"`
	AvgCtr      int32 `json:"avg_ctr"`
}

type AdsAnalyticsPacingHistory struct {
	ID                   int64          `json:"id"`
	EventTime            time.Time      `json:"event_time"`
	CampaignID           int32          `json:"campaign_id"`
	TotalBudgetCents     sql.NullInt64  `json:"total_budget_cents"`
	DailyBudgetCents     sql.NullInt64  `json:"daily_budget_cents"`
	RemainingBudgetCents sql.NullInt64  `json:"remaining_budget_cents"`
	SpentTodayCents      sql.NullInt64  `json:"spent_today_cents"`
	EffectiveTargetCents sql.NullInt64  `json:"effective_target_cents"`
	RemainingDays        sql.NullInt32  `json:"remaining_days"`
	CampaignTimeFactor   sql.NullString `json:"campaign_time_factor"`
	DailyTimeFactor      sql.NullString `json:"daily_time_factor"`
	Kp                   sql.NullString `json:"kp"`
	Ki                   sql.NullString `json:"ki"`
	MinMultiplier        sql.NullString `json:"min_multiplier"`
	MaxMultiplier        sql.NullString `json:"max_multiplier"`
	ErrorNormalized      sql.NullString `json:"error_normalized"`
	PTerm                sql.NullString `json:"p_term"`
	ITerm                sql.NullString `json:"i_term"`
	Urgency              sql.NullString `json:"urgency"`
	Adjustment           sql.NullString `json:"adjustment"`
	CumulativeError      sql.NullString `json:"cumulative_error"`
	PreviousMultiplier   sql.NullString `json:"previous_multiplier"`
	NewMultiplier        sql.NullString `json:"new_multiplier"`
	Status               sql.NullString `json:"status"`
	CreatedAt            sql.NullTime   `json:"created_at"`
}

type Advertiser struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Website   sql.NullString `json:"website"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type Campaign struct {
	ID           int32         `json:"id"`
	AdvertiserID sql.NullInt32 `json:"advertiser_id"`
	Name         string        `json:"name"`
	Status       string        `json:"status"`
	TotalBudget  sql.NullInt64 `json:"total_budget"`
	StartDate    time.Time     `json:"start_date"`
	EndDate      sql.NullTime  `json:"end_date"`
	CreatedAt    sql.NullTime  `json:"created_at"`
	UpdatedAt    sql.NullTime  `json:"updated_at"`
}

type Entity struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type IabTopic struct {
	ID       int32          `json:"id"`
	Name     string         `json:"name"`
	ParentID sql.NullInt32  `json:"parent_id"`
	Tier     int32          `json:"tier"`
	Type     sql.NullString `json:"type"`
}

type IabTopicMapping struct {
	ContentTopicID int32 `json:"content_topic_id"`
	ProductTopicID int32 `json:"product_topic_id"`
}

type PageChunkEmbedding struct {
	ID          int64          `json:"id"`
	PageUrlHash string         `json:"page_url_hash"`
	ChunkIndex  int32          `json:"chunk_index"`
	Content     sql.NullString `json:"content"`
	Embedding   interface{}    `json:"embedding"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type PageContext struct {
	ID          int64          `json:"id"`
	PageUrlHash string         `json:"page_url_hash"`
	Url         string         `json:"url"`
	Title       sql.NullString `json:"title"`
	Description sql.NullString `json:"description"`
	PublisherID sql.NullInt32  `json:"publisher_id"`
	Crawled     sql.NullBool   `json:"crawled"`
	ProcessedAt sql.NullTime   `json:"processed_at"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type PageEmbedding struct {
	ID          int64         `json:"id"`
	PageUrlHash string        `json:"page_url_hash"`
	Url         string        `json:"url"`
	Embedding   interface{}   `json:"embedding"`
	ChunkCount  sql.NullInt32 `json:"chunk_count"`
	CreatedAt   sql.NullTime  `json:"created_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
}

type PageEntity struct {
	ID          int64        `json:"id"`
	PageUrlHash string       `json:"page_url_hash"`
	EntityText  string       `json:"entity_text"`
	EntityType  string       `json:"entity_type"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type PageKeyword struct {
	ID             int64          `json:"id"`
	PageUrlHash    string         `json:"page_url_hash"`
	Keyword        string         `json:"keyword"`
	RelevanceScore sql.NullString `json:"relevance_score"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type PageTopic struct {
	ID             int64          `json:"id"`
	PageUrlHash    string         `json:"page_url_hash"`
	TopicID        int32          `json:"topic_id"`
	IabID          string         `json:"iab_id"`
	Name           sql.NullString `json:"name"`
	Tier           sql.NullInt32  `json:"tier"`
	RelevanceScore sql.NullString `json:"relevance_score"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type Publisher struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	Domain    string       `json:"domain"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
