// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: publishers.sql

package db

import (
	"context"
)

const createPublisher = `-- name: CreatePublisher :one
INSERT INTO publishers (name, domain)
VALUES ($1, $2)
RETURNING id, name, domain, created_at, updated_at
`

type CreatePublisherParams struct {
	Name   string `json:"name"`
	Domain string `json:"domain"`
}

func (q *Queries) CreatePublisher(ctx context.Context, arg CreatePublisherParams) (Publisher, error) {
	row := q.db.QueryRowContext(ctx, createPublisher, arg.Name, arg.Domain)
	var i Publisher
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePublisher = `-- name: DeletePublisher :exec
DELETE FROM publishers
WHERE id = $1
`

func (q *Queries) DeletePublisher(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deletePublisher, id)
	return err
}

const getPublisher = `-- name: GetPublisher :one
SELECT id, name, domain, created_at, updated_at FROM publishers
WHERE id = $1
`

func (q *Queries) GetPublisher(ctx context.Context, id int32) (Publisher, error) {
	row := q.db.QueryRowContext(ctx, getPublisher, id)
	var i Publisher
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublishers = `-- name: ListPublishers :many
SELECT id, name, domain, created_at, updated_at FROM publishers
ORDER BY created_at DESC
`

func (q *Queries) ListPublishers(ctx context.Context) ([]Publisher, error) {
	rows, err := q.db.QueryContext(ctx, listPublishers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Publisher
	for rows.Next() {
		var i Publisher
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePublisher = `-- name: UpdatePublisher :one
UPDATE publishers
SET name = $2,
    domain = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, domain, created_at, updated_at
`

type UpdatePublisherParams struct {
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	Domain string `json:"domain"`
}

func (q *Queries) UpdatePublisher(ctx context.Context, arg UpdatePublisherParams) (Publisher, error) {
	row := q.db.QueryRowContext(ctx, updatePublisher, arg.ID, arg.Name, arg.Domain)
	var i Publisher
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
