// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: targeting.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createAdTargetingCountry = `-- name: CreateAdTargetingCountry :one
INSERT INTO ad_targeting_country (ad_id, country_iso_code)
VALUES ($1, $2)
RETURNING id, ad_id, country_iso_code, updated_at
`

type CreateAdTargetingCountryParams struct {
	AdID           sql.NullInt32 `json:"ad_id"`
	CountryIsoCode string        `json:"country_iso_code"`
}

func (q *Queries) CreateAdTargetingCountry(ctx context.Context, arg CreateAdTargetingCountryParams) (AdTargetingCountry, error) {
	row := q.db.QueryRowContext(ctx, createAdTargetingCountry, arg.AdID, arg.CountryIsoCode)
	var i AdTargetingCountry
	err := row.Scan(
		&i.ID,
		&i.AdID,
		&i.CountryIsoCode,
		&i.UpdatedAt,
	)
	return i, err
}

const createAdTargetingDevice = `-- name: CreateAdTargetingDevice :one
INSERT INTO ad_targeting_device (ad_id, device_type)
VALUES ($1, $2)
RETURNING id, ad_id, device_type, updated_at
`

type CreateAdTargetingDeviceParams struct {
	AdID       sql.NullInt32 `json:"ad_id"`
	DeviceType string        `json:"device_type"`
}

func (q *Queries) CreateAdTargetingDevice(ctx context.Context, arg CreateAdTargetingDeviceParams) (AdTargetingDevice, error) {
	row := q.db.QueryRowContext(ctx, createAdTargetingDevice, arg.AdID, arg.DeviceType)
	var i AdTargetingDevice
	err := row.Scan(
		&i.ID,
		&i.AdID,
		&i.DeviceType,
		&i.UpdatedAt,
	)
	return i, err
}

const createAdTargetingEntity = `-- name: CreateAdTargetingEntity :one
INSERT INTO ad_targeting_entity (ad_id, entity_id, entity_type)
VALUES ($1, $2, $3)
RETURNING id, ad_id, entity_id, entity_type, updated_at
`

type CreateAdTargetingEntityParams struct {
	AdID       sql.NullInt32 `json:"ad_id"`
	EntityID   string        `json:"entity_id"`
	EntityType string        `json:"entity_type"`
}

func (q *Queries) CreateAdTargetingEntity(ctx context.Context, arg CreateAdTargetingEntityParams) (AdTargetingEntity, error) {
	row := q.db.QueryRowContext(ctx, createAdTargetingEntity, arg.AdID, arg.EntityID, arg.EntityType)
	var i AdTargetingEntity
	err := row.Scan(
		&i.ID,
		&i.AdID,
		&i.EntityID,
		&i.EntityType,
		&i.UpdatedAt,
	)
	return i, err
}

const createAdTargetingKeyword = `-- name: CreateAdTargetingKeyword :one
INSERT INTO ad_targeting_keyword (ad_id, keyword, relevance_score)
VALUES ($1, $2, $3)
RETURNING id, ad_id, keyword, relevance_score, updated_at
`

type CreateAdTargetingKeywordParams struct {
	AdID           sql.NullInt32  `json:"ad_id"`
	Keyword        string         `json:"keyword"`
	RelevanceScore sql.NullString `json:"relevance_score"`
}

func (q *Queries) CreateAdTargetingKeyword(ctx context.Context, arg CreateAdTargetingKeywordParams) (AdTargetingKeyword, error) {
	row := q.db.QueryRowContext(ctx, createAdTargetingKeyword, arg.AdID, arg.Keyword, arg.RelevanceScore)
	var i AdTargetingKeyword
	err := row.Scan(
		&i.ID,
		&i.AdID,
		&i.Keyword,
		&i.RelevanceScore,
		&i.UpdatedAt,
	)
	return i, err
}

const createAdTargetingTopic = `-- name: CreateAdTargetingTopic :one
INSERT INTO ad_targeting_topic (ad_id, topic_id, relevance_score)
VALUES ($1, $2, $3)
RETURNING id, ad_id, topic_id, relevance_score, updated_at
`

type CreateAdTargetingTopicParams struct {
	AdID           sql.NullInt32  `json:"ad_id"`
	TopicID        int32          `json:"topic_id"`
	RelevanceScore sql.NullString `json:"relevance_score"`
}

func (q *Queries) CreateAdTargetingTopic(ctx context.Context, arg CreateAdTargetingTopicParams) (AdTargetingTopic, error) {
	row := q.db.QueryRowContext(ctx, createAdTargetingTopic, arg.AdID, arg.TopicID, arg.RelevanceScore)
	var i AdTargetingTopic
	err := row.Scan(
		&i.ID,
		&i.AdID,
		&i.TopicID,
		&i.RelevanceScore,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdTargetingCountries = `-- name: GetAdTargetingCountries :many
SELECT id, ad_id, country_iso_code, updated_at FROM ad_targeting_country
WHERE ad_id = $1
`

func (q *Queries) GetAdTargetingCountries(ctx context.Context, adID sql.NullInt32) ([]AdTargetingCountry, error) {
	rows, err := q.db.QueryContext(ctx, getAdTargetingCountries, adID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdTargetingCountry
	for rows.Next() {
		var i AdTargetingCountry
		if err := rows.Scan(
			&i.ID,
			&i.AdID,
			&i.CountryIsoCode,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdTargetingCountriesByAdIds = `-- name: GetAdTargetingCountriesByAdIds :many
SELECT id, ad_id, country_iso_code, updated_at FROM ad_targeting_country
WHERE ad_id = ANY($1::int[])
ORDER BY ad_id
`

func (q *Queries) GetAdTargetingCountriesByAdIds(ctx context.Context, dollar_1 []int32) ([]AdTargetingCountry, error) {
	rows, err := q.db.QueryContext(ctx, getAdTargetingCountriesByAdIds, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdTargetingCountry
	for rows.Next() {
		var i AdTargetingCountry
		if err := rows.Scan(
			&i.ID,
			&i.AdID,
			&i.CountryIsoCode,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdTargetingDevices = `-- name: GetAdTargetingDevices :many
SELECT id, ad_id, device_type, updated_at FROM ad_targeting_device
WHERE ad_id = $1
`

func (q *Queries) GetAdTargetingDevices(ctx context.Context, adID sql.NullInt32) ([]AdTargetingDevice, error) {
	rows, err := q.db.QueryContext(ctx, getAdTargetingDevices, adID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdTargetingDevice
	for rows.Next() {
		var i AdTargetingDevice
		if err := rows.Scan(
			&i.ID,
			&i.AdID,
			&i.DeviceType,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdTargetingDevicesByAdIds = `-- name: GetAdTargetingDevicesByAdIds :many
SELECT id, ad_id, device_type, updated_at FROM ad_targeting_device
WHERE ad_id = ANY($1::int[])
ORDER BY ad_id
`

func (q *Queries) GetAdTargetingDevicesByAdIds(ctx context.Context, dollar_1 []int32) ([]AdTargetingDevice, error) {
	rows, err := q.db.QueryContext(ctx, getAdTargetingDevicesByAdIds, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdTargetingDevice
	for rows.Next() {
		var i AdTargetingDevice
		if err := rows.Scan(
			&i.ID,
			&i.AdID,
			&i.DeviceType,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdTargetingEntities = `-- name: GetAdTargetingEntities :many
SELECT id, ad_id, entity_id, entity_type, updated_at FROM ad_targeting_entity
WHERE ad_id = $1
`

func (q *Queries) GetAdTargetingEntities(ctx context.Context, adID sql.NullInt32) ([]AdTargetingEntity, error) {
	rows, err := q.db.QueryContext(ctx, getAdTargetingEntities, adID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdTargetingEntity
	for rows.Next() {
		var i AdTargetingEntity
		if err := rows.Scan(
			&i.ID,
			&i.AdID,
			&i.EntityID,
			&i.EntityType,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdTargetingEntitiesByAdIds = `-- name: GetAdTargetingEntitiesByAdIds :many
SELECT id, ad_id, entity_id, entity_type, updated_at FROM ad_targeting_entity
WHERE ad_id = ANY($1::int[])
ORDER BY ad_id
`

func (q *Queries) GetAdTargetingEntitiesByAdIds(ctx context.Context, dollar_1 []int32) ([]AdTargetingEntity, error) {
	rows, err := q.db.QueryContext(ctx, getAdTargetingEntitiesByAdIds, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdTargetingEntity
	for rows.Next() {
		var i AdTargetingEntity
		if err := rows.Scan(
			&i.ID,
			&i.AdID,
			&i.EntityID,
			&i.EntityType,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdTargetingKeywords = `-- name: GetAdTargetingKeywords :many
SELECT id, ad_id, keyword, relevance_score, updated_at FROM ad_targeting_keyword
WHERE ad_id = $1
`

func (q *Queries) GetAdTargetingKeywords(ctx context.Context, adID sql.NullInt32) ([]AdTargetingKeyword, error) {
	rows, err := q.db.QueryContext(ctx, getAdTargetingKeywords, adID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdTargetingKeyword
	for rows.Next() {
		var i AdTargetingKeyword
		if err := rows.Scan(
			&i.ID,
			&i.AdID,
			&i.Keyword,
			&i.RelevanceScore,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdTargetingKeywordsByAdIds = `-- name: GetAdTargetingKeywordsByAdIds :many
SELECT id, ad_id, keyword, relevance_score, updated_at FROM ad_targeting_keyword
WHERE ad_id = ANY($1::int[])
ORDER BY ad_id, relevance_score DESC
`

func (q *Queries) GetAdTargetingKeywordsByAdIds(ctx context.Context, dollar_1 []int32) ([]AdTargetingKeyword, error) {
	rows, err := q.db.QueryContext(ctx, getAdTargetingKeywordsByAdIds, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdTargetingKeyword
	for rows.Next() {
		var i AdTargetingKeyword
		if err := rows.Scan(
			&i.ID,
			&i.AdID,
			&i.Keyword,
			&i.RelevanceScore,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdTargetingTopics = `-- name: GetAdTargetingTopics :many
SELECT id, ad_id, topic_id, relevance_score, updated_at FROM ad_targeting_topic
WHERE ad_id = $1
`

func (q *Queries) GetAdTargetingTopics(ctx context.Context, adID sql.NullInt32) ([]AdTargetingTopic, error) {
	rows, err := q.db.QueryContext(ctx, getAdTargetingTopics, adID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdTargetingTopic
	for rows.Next() {
		var i AdTargetingTopic
		if err := rows.Scan(
			&i.ID,
			&i.AdID,
			&i.TopicID,
			&i.RelevanceScore,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdTargetingTopicsByAdIds = `-- name: GetAdTargetingTopicsByAdIds :many
SELECT att.id, att.ad_id, att.topic_id, att.relevance_score, att.updated_at, it.tier
FROM ad_targeting_topic att
JOIN iab_topics it ON att.topic_id = it.id
WHERE att.ad_id = ANY($1::int[])
ORDER BY att.ad_id, att.relevance_score DESC
`

type GetAdTargetingTopicsByAdIdsRow struct {
	ID             int64          `json:"id"`
	AdID           sql.NullInt32  `json:"ad_id"`
	TopicID        int32          `json:"topic_id"`
	RelevanceScore sql.NullString `json:"relevance_score"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	Tier           int32          `json:"tier"`
}

func (q *Queries) GetAdTargetingTopicsByAdIds(ctx context.Context, dollar_1 []int32) ([]GetAdTargetingTopicsByAdIdsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAdTargetingTopicsByAdIds, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdTargetingTopicsByAdIdsRow
	for rows.Next() {
		var i GetAdTargetingTopicsByAdIdsRow
		if err := rows.Scan(
			&i.ID,
			&i.AdID,
			&i.TopicID,
			&i.RelevanceScore,
			&i.UpdatedAt,
			&i.Tier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
