// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: taxonomy.sql

package db

import (
	"context"
	"database/sql"
)

const countIABTopicMappings = `-- name: CountIABTopicMappings :one
SELECT COUNT(*) FROM iab_topic_mapping
`

func (q *Queries) CountIABTopicMappings(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIABTopicMappings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIABTopics = `-- name: CountIABTopics :one
SELECT COUNT(*) FROM iab_topics
`

func (q *Queries) CountIABTopics(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIABTopics)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIABTopic = `-- name: CreateIABTopic :exec
INSERT INTO iab_topics (
    id,
    name,
    parent_id,
    tier,
    type
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO NOTHING
`

type CreateIABTopicParams struct {
	ID       int32          `json:"id"`
	Name     string         `json:"name"`
	ParentID sql.NullInt32  `json:"parent_id"`
	Tier     int32          `json:"tier"`
	Type     sql.NullString `json:"type"`
}

func (q *Queries) CreateIABTopic(ctx context.Context, arg CreateIABTopicParams) error {
	_, err := q.db.ExecContext(ctx, createIABTopic,
		arg.ID,
		arg.Name,
		arg.ParentID,
		arg.Tier,
		arg.Type,
	)
	return err
}

const createIABTopicMapping = `-- name: CreateIABTopicMapping :exec
INSERT INTO iab_topic_mapping (
    content_topic_id,
    product_topic_id
) VALUES ($1, $2)
ON CONFLICT (content_topic_id, product_topic_id) DO NOTHING
`

type CreateIABTopicMappingParams struct {
	ContentTopicID int32 `json:"content_topic_id"`
	ProductTopicID int32 `json:"product_topic_id"`
}

func (q *Queries) CreateIABTopicMapping(ctx context.Context, arg CreateIABTopicMappingParams) error {
	_, err := q.db.ExecContext(ctx, createIABTopicMapping, arg.ContentTopicID, arg.ProductTopicID)
	return err
}

const getContentTopicsByProductTopic = `-- name: GetContentTopicsByProductTopic :many
SELECT c.id, c.name, c.parent_id, c.tier, c.type FROM iab_topics c
INNER JOIN iab_topic_mapping m ON c.id = m.content_topic_id
WHERE m.product_topic_id = $1
`

func (q *Queries) GetContentTopicsByProductTopic(ctx context.Context, productTopicID int32) ([]IabTopic, error) {
	rows, err := q.db.QueryContext(ctx, getContentTopicsByProductTopic, productTopicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IabTopic
	for rows.Next() {
		var i IabTopic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.Tier,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIABTopic = `-- name: GetIABTopic :one
SELECT id, name, parent_id, tier, type FROM iab_topics
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetIABTopic(ctx context.Context, id int32) (IabTopic, error) {
	row := q.db.QueryRowContext(ctx, getIABTopic, id)
	var i IabTopic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.Tier,
		&i.Type,
	)
	return i, err
}

const getProductTopicsByContentTopic = `-- name: GetProductTopicsByContentTopic :many
SELECT p.id, p.name, p.parent_id, p.tier, p.type FROM iab_topics p
INNER JOIN iab_topic_mapping m ON p.id = m.product_topic_id
WHERE m.content_topic_id = $1
`

func (q *Queries) GetProductTopicsByContentTopic(ctx context.Context, contentTopicID int32) ([]IabTopic, error) {
	rows, err := q.db.QueryContext(ctx, getProductTopicsByContentTopic, contentTopicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IabTopic
	for rows.Next() {
		var i IabTopic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.Tier,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIABTopics = `-- name: ListIABTopics :many
SELECT id, name, parent_id, tier, type FROM iab_topics
ORDER BY id
`

func (q *Queries) ListIABTopics(ctx context.Context) ([]IabTopic, error) {
	rows, err := q.db.QueryContext(ctx, listIABTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IabTopic
	for rows.Next() {
		var i IabTopic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.Tier,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIABTopicsByType = `-- name: ListIABTopicsByType :many
SELECT id, name, parent_id, tier, type FROM iab_topics
WHERE type = $1
ORDER BY id
`

func (q *Queries) ListIABTopicsByType(ctx context.Context, type_ sql.NullString) ([]IabTopic, error) {
	rows, err := q.db.QueryContext(ctx, listIABTopicsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IabTopic
	for rows.Next() {
		var i IabTopic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.Tier,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
