#!/usr/bin/env python3
"""
Generate relevance annotations for page-ad pairs using LLM-as-judge.

Uses the **pooling method**: only the top-K ranked ads per page are judged
(not the full matrix). Labels are generated by Claude Haiku in batched
concurrent requests, then exported as CSV (for human review) and JSON
(for Go test consumption).

Workflow:
  1. Run:  python scripts/generate_annotations.py
           -> calls Claude Haiku to label top-K ads per page
           -> writes annotations.csv + annotations.json to data/eval/
  2. (Optional) Open annotations.csv to spot-check low-confidence rows
  3. Run:  python scripts/generate_annotations.py --import
           -> re-imports an edited CSV back to annotations.json
  4. Run:  make eval-nlp
           -> Go test loads annotations.json as ground-truth overrides

Usage:
    python scripts/generate_annotations.py [--top-k 50] [--batch-size 10] [--workers 8]
    python scripts/generate_annotations.py --import
"""

import argparse
import csv
import json
import logging
import os
import random
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from tqdm import tqdm

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
DATA_DIR = PROJECT_ROOT / "data"
EVAL_DIR = DATA_DIR / "eval"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("generate_annotations")

MODEL = "claude-haiku-4-5-20251001"

MAX_RETRIES = 5
INITIAL_BACKOFF = 2.0   # seconds
MAX_BACKOFF = 60.0       # seconds


class RateLimiter:

    def __init__(self, requests_per_second: float):
        self._min_interval = 1.0 / requests_per_second if requests_per_second > 0 else 0
        self._lock = threading.Lock()
        self._last = 0.0

    def wait(self):
        with self._lock:
            now = time.monotonic()
            wait_time = self._last + self._min_interval - now
            if wait_time > 0:
                time.sleep(wait_time)
            self._last = time.monotonic()



def load_pages():
    with open(EVAL_DIR / "nlp_page_contexts.json") as f:
        return json.load(f)


def load_ads():
    with open(EVAL_DIR / "nlp_ad_contexts.json") as f:
        return json.load(f)


def cosine_sim(a, b):
    if not a or not b or len(a) != len(b):
        return 0.0
    dot = sum(x * y for x, y in zip(a, b))
    norm_a = sum(x * x for x in a) ** 0.5
    norm_b = sum(x * x for x in b) ** 0.5
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return dot / (norm_a * norm_b)


def keyword_overlap(page_kws, ad_kws):
    page_set = {k.lower() for k in page_kws}
    ad_set = {k.lower() for k in ad_kws}
    return len(page_set & ad_set)


def top_keys(d, n=5):
    """Return top-n keys from a dict sorted by value descending."""
    if isinstance(d, dict):
        return sorted(d, key=lambda k: d[k], reverse=True)[:n]
    if isinstance(d, list):
        return d[:n]
    return []


SYSTEM_PROMPT = """\
You are an ad-relevance judge for a contextual advertising system.
You evaluate whether an advertisement is contextually relevant to a webpage.

A relevant ad is one that a reader of this page would reasonably find
interesting, useful, or topically aligned based on the page's content.

You will receive a batch of page-ad pairs. For each pair, respond with a
JSON object on its own line with these fields:
- "id": the pair ID (string, echoed back)
- "relevant": 1 if relevant, 0 if not
- "confidence": "high", "medium", or "low"
- "reason": a short one-sentence justification

Respond ONLY with one JSON object per line, no other text. Example:
{"id": "0", "relevant": 1, "confidence": "high", "reason": "Sports betting ad matches a football match report."}
{"id": "1", "relevant": 0, "confidence": "high", "reason": "Luxury fashion ad has no connection to a political news article."}
"""


def format_pair(pair_id, page, ad):
    """Format a single page-ad pair for the prompt."""
    page_title = page.get("meta_data", {}).get("title", "")[:100]
    page_url = page.get("meta_data", {}).get("url", "")
    page_kws = ", ".join(top_keys(page.get("keywords", {}), 8))
    page_topics = ", ".join(
        t.get("name", "") for t in list(page.get("topics", {}).values())[:4]
    )

    ad_headline = ad.get("headline", "")
    ad_desc = ad.get("description", "")[:120]
    ad_category = ad.get("content_category", "")
    ad_kws = ", ".join(top_keys(ad.get("keywords", {}), 6))

    return (
        f"--- Pair {pair_id} ---\n"
        f"PAGE:\n"
        f"  Title: {page_title}\n"
        f"  URL: {page_url}\n"
        f"  Keywords: {page_kws}\n"
        f"  Topics: {page_topics}\n"
        f"AD:\n"
        f"  Headline: {ad_headline}\n"
        f"  Description: {ad_desc}\n"
        f"  Category: {ad_category}\n"
        f"  Keywords: {ad_kws}\n"
    )


def judge_batch(client, pairs, rate_limiter=None):
    """
    Send a batch of (pair_id, page, ad) tuples to Claude and parse results.
    Returns a dict of pair_id -> {relevant, confidence, reason}.
    Retries with exponential backoff on 429 / 5xx errors.
    """
    prompt_parts = []
    for pair_id, page, ad in pairs:
        prompt_parts.append(format_pair(pair_id, page, ad))

    user_msg = (
        "Judge the following page-ad pairs for contextual relevance.\n"
        "Respond with one JSON object per line.\n\n"
        + "\n".join(prompt_parts)
    )

    backoff = INITIAL_BACKOFF
    last_err = None

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            if rate_limiter:
                rate_limiter.wait()

            response = client.messages.create(
                model=MODEL,
                max_tokens=2048,
                system=SYSTEM_PROMPT,
                messages=[{"role": "user", "content": user_msg}],
            )
            break  # success
        except Exception as e:
            last_err = e
            err_str = str(e)
            status = getattr(e, "status_code", None)
            is_rate_limit = status == 429 or "429" in err_str or "rate" in err_str.lower()
            is_server_err = status is not None and status >= 500

            if is_rate_limit or is_server_err:
                # Parse Retry-After header if the SDK exposes it
                retry_after = getattr(e, "retry_after", None)
                sleep_time = float(retry_after) if retry_after else backoff
                jitter = random.uniform(0, sleep_time * 0.25)
                total_sleep = sleep_time + jitter

                logger.warning(
                    f"Retryable error (attempt {attempt}/{MAX_RETRIES}): "
                    f"status={status} — sleeping {total_sleep:.1f}s"
                )
                time.sleep(total_sleep)
                backoff = min(backoff * 2, MAX_BACKOFF)
                continue
            else:
                raise  # non-retryable error
    else:
        # Exhausted all retries
        logger.error(f"Batch failed after {MAX_RETRIES} retries: {last_err}")
        return {}

    results = {}
    text = response.content[0].text.strip()
    for line in text.split("\n"):
        line = line.strip()
        if not line:
            continue
        try:
            obj = json.loads(line)
            pid = str(obj.get("id", ""))
            results[pid] = {
                "relevant": int(obj.get("relevant", 0)),
                "confidence": obj.get("confidence", "low"),
                "reason": obj.get("reason", ""),
            }
        except (json.JSONDecodeError, ValueError):
            logger.warning(f"Failed to parse LLM line: {line[:100]}")
            continue

    return results



def generate(output_dir: Path, top_k: int, batch_size: int, workers: int, rps: float):
    """Generate annotations using LLM-as-judge with batched concurrent calls."""
    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not api_key:
        print("ERROR: ANTHROPIC_API_KEY environment variable not set.")
        print("  export ANTHROPIC_API_KEY=sk-ant-...")
        sys.exit(1)

    try:
        import anthropic
    except ImportError:
        print("ERROR: anthropic package not installed. pip install anthropic")
        sys.exit(1)

    client = anthropic.Anthropic(api_key=api_key)

    pages = load_pages()
    ads = load_ads()
    logger.info(f"Loaded {len(pages)} pages, {len(ads)} ads")

    # Build all (page, top-K ads) pairs sorted by cosine similarity
    all_pairs = []  # list of (pair_id, page, ad, sim, kw_overlap)
    pair_id = 0

    for page in tqdm(pages, desc="Building page-ad pairs", unit="page"):
        page_emb = page.get("page_embedding", [])
        page_kws = page.get("keywords", {})

        scored = []
        for ad in ads:
            sim = cosine_sim(page_emb, ad.get("embedding", []))
            scored.append((sim, ad))
        scored.sort(key=lambda x: -x[0])

        for sim, ad in scored[:top_k]:
            kw_ov = keyword_overlap(page_kws, ad.get("keywords", {}))
            all_pairs.append((str(pair_id), page, ad, sim, kw_ov))
            pair_id += 1

    logger.info(f"Total pairs to judge: {len(all_pairs)} ({len(pages)} pages x top-{top_k})")

    # Split into batches for the LLM
    batches = []
    for i in range(0, len(all_pairs), batch_size):
        chunk = all_pairs[i : i + batch_size]
        batches.append([(pid, pg, ad) for pid, pg, ad, _, _ in chunk])

    logger.info(f"Sending {len(batches)} batches (size={batch_size}) with {workers} workers...")

    # Rate limiter: throttle across all workers
    rate_limiter = RateLimiter(requests_per_second=rps)

    # Call LLM concurrently
    llm_results = {}
    t0 = time.time()

    with ThreadPoolExecutor(max_workers=workers) as pool:
        future_to_idx = {
            pool.submit(judge_batch, client, batch, rate_limiter): idx
            for idx, batch in enumerate(batches)
        }
        with tqdm(total=len(batches), desc="LLM judging batches", unit="batch") as pbar:
            for future in as_completed(future_to_idx):
                idx = future_to_idx[future]
                try:
                    batch_results = future.result()
                    llm_results.update(batch_results)
                    pbar.set_postfix(results=len(llm_results), refresh=False)
                except Exception:
                    logger.exception(f"  Batch {idx + 1}/{len(batches)} FAILED")
                pbar.update(1)

    elapsed = time.time() - t0
    logger.info(f"LLM judging complete in {elapsed:.1f}s — got {len(llm_results)}/{len(all_pairs)} results")

    # Build output rows
    rows = []
    for pid, page, ad, sim, kw_ov in all_pairs:
        llm = llm_results.get(pid, {})

        relevant = llm.get("relevant", 1 if (sim >= 0.5 or kw_ov >= 3) else 0)
        source = "llm" if pid in llm_results else "auto"
        confidence = llm.get("confidence", "")
        reason = llm.get("reason", "")

        rows.append({
            "page_hash": page["page_url_hash"],
            "page_title": page.get("meta_data", {}).get("title", "")[:80],
            "page_url": page.get("meta_data", {}).get("url", ""),
            "page_theme": page.get("theme", ""),
            "rank": int(pid) % top_k + 1,
            "ad_id": ad["ad_id"],
            "ad_headline": ad.get("headline", "")[:80],
            "ad_category": ad.get("content_category", ""),
            "cosine_sim": round(sim, 4),
            "kw_overlap": kw_ov,
            "relevant": relevant,
            "confidence": confidence,
            "source": source,
            "reason": reason,
            "notes": "",
        })

    # Write CSV
    csv_path = output_dir / "annotations.csv"
    fieldnames = [
        "page_hash", "page_title", "page_url", "page_theme",
        "rank", "ad_id", "ad_headline", "ad_category",
        "cosine_sim", "kw_overlap",
        "relevant", "confidence", "source", "reason", "notes",
    ]
    with open(csv_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    # Write JSON ground truth
    ground_truth = {}
    for row in rows:
        ph = row["page_hash"]
        if ph not in ground_truth:
            ground_truth[ph] = {}
        ground_truth[ph][str(row["ad_id"])] = row["relevant"] == 1
    json_path = output_dir / "annotations.json"
    with open(json_path, "w") as f:
        json.dump(ground_truth, f, indent=2)

    # Stats
    n_rel = sum(1 for r in rows if r["relevant"] == 1)
    n_llm = sum(1 for r in rows if r["source"] == "llm")
    n_high = sum(1 for r in rows if r["confidence"] == "high")
    n_low = sum(1 for r in rows if r["confidence"] == "low")

    logger.info(
        f"\nResults:\n"
        f"  CSV:  {csv_path} ({len(rows)} rows)\n"
        f"  JSON: {json_path}\n"
        f"  Relevant: {n_rel}/{len(rows)} ({100*n_rel/max(len(rows),1):.1f}%)\n"
        f"  LLM-judged: {n_llm}, Auto-fallback: {len(rows) - n_llm}\n"
        f"  Confidence: {n_high} high, {len(rows) - n_high - n_low} medium, {n_low} low\n"
        f"\nTo spot-check, open the CSV and filter by confidence=low or source=auto.\n"
        f"Edit the 'relevant' column, set source to 'human', then run:\n"
        f"  python scripts/generate_annotations.py --import"
    )


def import_csv(output_dir: Path):
    """Read an edited CSV and re-export annotations.json."""
    csv_path = output_dir / "annotations.csv"
    if not csv_path.exists():
        print(f"Error: {csv_path} not found. Run without --import first.")
        sys.exit(1)

    with open(csv_path, newline="") as f:
        rows = list(csv.DictReader(f))

    ground_truth = {}
    stats = {"total": 0, "relevant": 0, "human": 0, "llm": 0}

    for row in rows:
        ph = row["page_hash"]
        if ph not in ground_truth:
            ground_truth[ph] = {}
        is_rel = str(row.get("relevant", "0")).strip() == "1"
        ground_truth[ph][row["ad_id"]] = is_rel
        stats["total"] += 1
        if is_rel:
            stats["relevant"] += 1
        src = row.get("source", "").strip()
        if src == "human":
            stats["human"] += 1
        elif src == "llm":
            stats["llm"] += 1

    json_path = output_dir / "annotations.json"
    with open(json_path, "w") as f:
        json.dump(ground_truth, f, indent=2)

    print(f"Wrote {json_path}")
    print(f"  Total: {stats['total']}, Relevant: {stats['relevant']}")
    print(f"  Sources: {stats['llm']} llm, {stats['human']} human, "
          f"{stats['total'] - stats['llm'] - stats['human']} auto")


def main():
    parser = argparse.ArgumentParser(
        description="Generate relevance annotations using Claude Haiku as judge"
    )
    parser.add_argument(
        "--import", dest="do_import", action="store_true",
        help="Import an edited CSV back to annotations.json",
    )
    parser.add_argument("--top-k", type=int, default=50,
                        help="Top-K ads per page to judge (default: 50)")
    parser.add_argument("--batch-size", type=int, default=10,
                        help="Page-ad pairs per LLM request (default: 10)")
    parser.add_argument("--workers", type=int, default=2,
                        help="Concurrent LLM requests (default: 4)")
    parser.add_argument("--rps", type=float, default=1.0,
                        help="Max requests per second to the API (default: 1.0)")
    parser.add_argument("--output-dir", type=str, default=str(EVAL_DIR),
                        help=f"Output directory (default: {EVAL_DIR})")
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if args.do_import:
        import_csv(output_dir)
    else:
        generate(output_dir, args.top_k, args.batch_size, args.workers, args.rps)


if __name__ == "__main__":
    main()

